// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiU86OTMViwxsKEwlGEkjT-tXh4oFdIsY',
    appId: '1:841128695295:web:8057f0a0d84855c128c3ca',
    messagingSenderId: '841128695295',
    projectId: 'daleal-c9703',
    authDomain: 'daleal-c9703.firebaseapp.com',
    storageBucket: 'daleal-c9703.appspot.com',
    measurementId: 'G-82FE5HNQ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbg2fA1uSVPbN4xrrgGApxihCULud5wO8',
    appId: '1:841128695295:android:c658a51354a63cc128c3ca',
    messagingSenderId: '841128695295',
    projectId: 'daleal-c9703',
    storageBucket: 'daleal-c9703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIr7hx8Z5JHBPkCIyzo5DA7BY0TzXzOg',
    appId: '1:841128695295:ios:ee77ef65b1eaf47c28c3ca',
    messagingSenderId: '841128695295',
    projectId: 'daleal-c9703',
    storageBucket: 'daleal-c9703.appspot.com',
    iosBundleId: 'com.example.daleal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIr7hx8Z5JHBPkCIyzo5DA7BY0TzXzOg',
    appId: '1:841128695295:ios:50a18d03d266160228c3ca',
    messagingSenderId: '841128695295',
    projectId: 'daleal-c9703',
    storageBucket: 'daleal-c9703.appspot.com',
    iosBundleId: 'com.example.daleal.RunnerTests',
  );
}
